---
title: "ESM 244 Lab 5"
author: "Patrick Pelegri-O'Day"
date: "2/3/2022"
output: html_document
---

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)

### for part 1, PCA:
library(ggfortify)
library(palmerpenguins)
library(patchwork)

### for part 2, ggplot customization:
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)
```

## Part 1: PCA (Principal Components Analysis)

```{r}
penguin_clean <- penguins %>% 
  drop_na()

penguin_pca <- penguin_clean %>% 
  select(body_mass_g, ends_with('_mm')) %>% 
  scale() %>% # make all variables on same scale. Another option is use `scale = TRUE` argument within prcomp()
  prcomp()
```

#### Biplot by hand
```{r}
loadings_df <- data.frame(penguin_pca$rotation) %>% 
  mutate(axis = row.names(.)) 

new_pts_df <- data.frame(penguin_pca$x) # refers to all penguin observations based on their coordinates with the new PC system as opposed to the original axes

ggplot() + 
  geom_point(data = new_pts_df, aes(x = PC1, y = PC2), color = 'blue') +
  geom_segment(data = loadings_df, x = 0, y = 0,
               aes(xend = PC1, yend = PC2, group = axis),
               arrow = arrow(length = unit(0.25, 'cm'))) +
  geom_text(data = loadings_df,
            aes(x = PC1, y = PC2, label = axis),
            vjust = 0, nudge_y = .02) +
  theme_minimal()
```

```{r}
autoplot(penguin_pca,
         data = penguin_clean,
         loadings = TRUE,
         colour = 'species', # gotta use the british spelling for this package
         loadings.label = TRUE, # show labels of original vectors
         loadings.colour = 'black',
         loadings.label.colour = 'black',
         loadings.label.vjust = -0.5) +
  scale_color_manual(values = c('darkslateblue', 'cornsilk4', 'orange4')) +
  theme_minimal()
```

## Screeplot by hand

```{r}
sd_vec <- penguin_pca$sdev
var_vec <- sd_vec^2

pc_names <- colnames(penguin_pca$rotation)
pct_expl_df <- data.frame(v = var_vec,
                          pct_v = var_vec / sum(var_vec),
                          pc = fct_inorder(pc_names)) %>% 
  mutate(pct_lbl = paste0(round(pct_v * 100, 1), '%')) # converts arguments to strings then concatenates them

ggplot(pct_expl_df, aes(x = pc, y = v)) +
  geom_col() + 
  geom_text(aes(label = pct_label, vjust = 0, nudge_y = 0.0005)) +
  labs(x = "principle component", y = "variance estimated")
```

```{r}
screeplot(penguin_pca, type = 'lines')
screeplot(penguin_pca, type = 'barplot')
```

# Part 2: ggplot customization, reading in different file types

```{r}
fish_noaa <- read_excel(here('data', 'foss_landings.xlsx')) %>% 
  janitor::clean_names() %>% 
  mutate(across(where(is.character), tolower)) %>% # convert all values into characters
  mutate(nmfs_name = str_sub(nmfs_name, end = -4)) %>% 
  filter(confidentiality == 'public')
```

```{r}
fish_plot <- ggplot(data = fish_noaa, aes(x = year, 
                                          y = pounds, 
                                          group = nmfs_name)) +
  geom_line(aes(color = nmfs_name)) +
  theme_minimal()

ggplotly(fish_plot)

ggplot(data = fish_noaa, aes(x = year, y = pounds, group = nmfs_name)) +
  geom_line(aes(color = nmfs_name)) +
  gghighlight(max(pounds) > 1e8) + # highlight based on values specified
  theme_minimal()
```

## read in data from URL and practice some lubridate

```{r}
monroe_wt <- read_csv('https://raw.githubusercontent.com/oharac/esm244_w22_lab5/master/data/MWTP_Elec_Daily.csv') %>% 
  janitor::clean_names()

monroe_ts <- monroe_wt %>% 
  mutate(date = lubridate::mdy(date)) %>% 
  mutate(record_month = lubridate::month(date),
         month_name = month.abb[record_month]) %>% 
  mutate(month_name = fct_reorder(month_name, record_month))

ggplot(data = monroe_ts, aes(x = month_name, y = total_kwh)) + 
  geom_jitter(aes(color = month_name),
              show.legend = FALSE,
              alpha = 0.5,
              size = 0.3, 
              width = 0.2) +
  theme_classic()
```




